In [39]:
import cv2
print(cv2.__version__)

4.5.5


In [40]:
#read the image using imread method
import cv2
img=cv2.imread('lena5.jpg',0)
print(img)

[[159 159 159 ... 166 156 148]
 [159 159 159 ... 168 156 148]
 [159 159 159 ... 167 154 145]
 ...
 [ 52  52  52 ... 104 107 109]
 [ 52  52  52 ... 107 110 112]
 [ 52  52  52 ... 109 112 114]]


In [42]:
#display the image using imshow method
cv2.imshow('image',img)
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()
elif k==ord('s'):
    cv2.imwrite('lena5_copy.png',img)
    cv2.destroyAllWindows()
    

In [38]:
cv2.imwrite('lena5_copy.png',img)

True

# CAPTURE THE LIVE STREAM FROM CAMERA

In [2]:
import  cv2
cap = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi',fourcc,20.0,(680,480))
print(cap.isOpened())
while(cap.isOpened()):
    ret, frame=cap.read()
    if ret == True:
        print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        out.write(frame)
        gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        cv2.imshow('frame',gray)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
        else:
            break
cap.release()
out.release()
cv2.destroyAllWindows()

True
640.0
480.0


In [18]:
#Draw the Geometric shapes in the images
import numpy as np
import cv2
img=cv2.imread('lena5.jpg',1)
img = cv2.line(img, (0,0),(255,255),(0,255,0),10)
img = cv2.arrowedLine(img,(0,255),(255,255),(255,0,0),10)
img = cv2.rectangle(img,(380,0),(510,128),(0,0,255),10) # if wwe give -1 fully covered the color
img = cv2.circle(img,(447,63),63,(0,255,0),-1)
font = cv2.FONT_HERSHEY_SIMPLEX
img = cv2.putText(img,'OpenCV',(10,500),font,4,(255,255,255),10,cv2.LINE_AA)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
def fun_x(x):
    x=x+'2'
    x=x*2
    return x
print(fun_x('python'))

python2python2


In [2]:
import cv2
cap = cv2.VideoCapture(0)
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
cap.set(3,1208)
cap.set(4,720)

print(cap.get(3))
print(cap.get(4))
while(cap.isOpened()):
    ret,frame = cap.read()
    if ret == True:
        gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        cv2.imshow('frame',gray)
        if cv2.waitKey(0) & 0xFF == ord('q'):
            break
        else:
            break
cap.release()
cv2.destroyAllWindows()

640.0
480.0
960.0
540.0


In [4]:
import cv2
cap = cv2.VideoCapture(0)
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
cap.set(3,1208)
cap.set(4,720)

print(cap.get(3))
print(cap.get(4))
while(cap.isOpened()):
    ret,frame = cap.read()
    if ret == True:
        font = cv2.FONT_HERSHEY_SIMPLEX
        text = 'Width :'+ str(cap.get(3)) + ' Height:' + str(cap.get(4))
        frame = cv2.putText(frame,text,(10,50),font,1,(0,255,255),2,cv2.LINE_AA)
        cv2.imshow('frame',frame)
        if cv2.waitKey(0) & 0xFF == ord('q'):
            break
        else:
            break
cap.release()
cv2.destroyAllWindows()

640.0
480.0
960.0
540.0


In [5]:
#print the live date and time
import cv2
import datetime
cap = cv2.VideoCapture(0)
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
#cap.set(3,1208)
#cap.set(4,720)

#print(cap.get(3))
#print(cap.get(4))
while(cap.isOpened()):
    ret,frame = cap.read()
    if ret == True:
        font = cv2.FONT_HERSHEY_SIMPLEX
        text = 'Width :'+ str(cap.get(3)) + ' Height:' + str(cap.get(4))
        datet = str(datetime.datetime.now())
        frame = cv2.putText(frame,datet,(10,50),font,1,(0,255,255),2,cv2.LINE_AA)
        cv2.imshow('frame',frame)
        if cv2.waitKey(0) & 0xFF == ord('q'):
            break
        else:
            break
cap.release()
cv2.destroyAllWindows()

640.0
480.0


# HOW TO HANDLE THE MOUSE EVENT

In [7]:
import numpy as np
import cv2

events = [i for i in dir(cv2) if 'EVENT' in i]
print(events)

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


In [2]:
import numpy as np
import cv2

def click_event(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(x,' ,' ,y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY = str(x) + ' ,' +str(y)
        cv2.putText(img,strXY,(x,y),font,1,(255,255,0),2)
        cv2.imshow('image',img)
    if event == cv2.EVENT_RBUTTONDOWN:
        blue = img[y,x,0]
        green = img[y,x,1]
        red = img[y,x,2]
        font = cv2.FONT_HERSHEY_SIMPLEX
        strBGR = str(blue) + ' ,' +str(green) + ' ,' +str(red)
        cv2.putText(img,strBGR,(x,y),font,1,(0,255,255),2)
        cv2.imshow('image',img)
img = np.zeros((512,512,3),np.uint8)
cv2.imshow('image',img)

cv2.setMouseCallback('image',click_event)
cv2.waitKey(0)
cv2.destroyAllWindows()

378  , 305
236  , 151
197  , 185
182  , 370


In [3]:
import numpy as np
import cv2

def click_event(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(x,' ,' ,y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY = str(x) + ' ,' +str(y)
        cv2.putText(img,strXY,(x,y),font,1,(255,255,0),2)
        cv2.imshow('image',img)
    if event == cv2.EVENT_RBUTTONDOWN:
        blue = img[y,x,0]
        green = img[y,x,1]
        red = img[y,x,2]
        font = cv2.FONT_HERSHEY_SIMPLEX
        strBGR = str(blue) + ' ,' +str(green) + ' ,' +str(red)
        cv2.putText(img,strBGR,(x,y),font,1,(0,255,255),2)
        cv2.imshow('image',img)
#img = np.zeros((512,512,3),np.uint8)
img = cv2.imread('lena5.jpg')
cv2.imshow('image',img)

cv2.setMouseCallback('image',click_event)
cv2.waitKey(0)
cv2.destroyAllWindows()

157  , 82
118  , 161
84  , 247
65  , 282


In [4]:
import numpy as np
import cv2

def click_event(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img,(x,y),3,(0,0,255),-1)
        points.append((x,y))
        if len(points)>=2:
            cv2.line(img,points[-1],points[-2],(255,0,0),5)
        
        
        cv2.imshow('image',img)
img = np.zeros((512,512,3),np.uint8)
#img = cv2.imread('lena5.jpg')
cv2.imshow('image',img)
points = []
cv2.setMouseCallback('image',click_event)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
import numpy as np
import cv2

def click_event(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDOWN:
        blue = img[x,y,0]
        green = img[x,y,1]
        red = img[x,y,2]
        cv2.circle(img,(x,y),3,(0,0,255),-1)
        mycolorimage = np.zeros((512,512,3),np.uint8)
        mycolorimage[:] = [blue,green,red]
        cv2.imshow('color',mycolorimage)
#img = np.zeros((512,512,3),np.uint8)
img = cv2.imread('lena5.jpg')
cv2.imshow('image',img)
points = []
cv2.setMouseCallback('image',click_event)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
import numpy as np
import cv2
img = cv2.imread('lena5.jpg')

print(img.shape)# it returns the number of rows coloumns and channel
print(img.size) # it returns the image pixel
print(img.dtype) # image datatype
b,g,r=cv2.split(img)
img = cv2.merge((b,g,r))

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(512, 512, 3)
786432
uint8


In [11]:
# ROI region of intrest of image
import numpy as np
import cv2
img = cv2.imread('messi.jpg')

print(img.shape)# it returns the number of rows coloumns and channel
print(img.size) # it returns the image pixel
print(img.dtype) # image datatype
b,g,r=cv2.split(img)
img = cv2.merge((b,g,r))
hat = img[280:340,330:390]
img[273:333,100:160] = hat
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(342, 548, 3)
562248
uint8


In [14]:
# ROI region of intrest of image
import numpy as np
import cv2
img = cv2.imread('messi.jpg')
img2 = cv2.imread('lena5.jpg')


print(img.shape)# it returns the number of rows coloumns and channel
print(img.size) # it returns the image pixel
print(img.dtype) # image datatype
b,g,r=cv2.split(img)
img = cv2.merge((b,g,r))
hat = img[280:340,330:390]
img[273:333,100:160] = hat
img = cv2.resize(img,(512,512))
img2 = cv2.resize(img2,(512,512))

img3=cv2.add(img,img2)
cv2.imshow('image',img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

(342, 548, 3)
562248
uint8


In [18]:
# ROI region of intrest of image
import numpy as np
import cv2
img = cv2.imread('messi.jpg')
img2 = cv2.imread('lena5.jpg')


print(img.shape)# it returns the number of rows coloumns and channel
print(img.size) # it returns the image pixel
print(img.dtype) # image datatype
b,g,r=cv2.split(img)
img = cv2.merge((b,g,r))
hat = img[280:340,330:390]
img[273:333,100:160] = hat
img = cv2.resize(img,(512,512))
img2 = cv2.resize(img2,(512,512))

img3=cv2.addWeighted(img,.5,img2,.5,0)
cv2.imshow('image',img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

(342, 548, 3)
562248
uint8


# BITWISE OPERATION

In [23]:
import cv2
import numpy as np
img1 = np.zeros((250,500,3),np.uint8)
img1 = cv2.rectangle(img1,(200,0),(300,100),(255,255,255),-1)
img2 = np.zeros((250,500,3),np.uint8)

bitAnd = cv2.bitwise_and(img2,img1)

cv2.imshow('img1',img1)
cv2.imshow('img2',img2)
cv2.imshow('bitAnd',bitAnd)
cv2.waitKey(0)
cv2.destroyAllWindows()

# TRACKBAR IN OPEN CV

In [33]:
import numpy as np
import cv2 as cv

def nothing(x):
    print(x)

img = np.zeros((300,512,3),np.uint8)
cv.namedWindow('image')
cv.createTrackbar('B','image',0,255,nothing)
cv.createTrackbar('G','image',0,255,nothing)
cv.createTrackbar('R','image',0,255,nothing)


while(1):
    cv.imshow('image',img)
    k = cv.waitKey(1) & 0xFF
    if k==27:
        break
        
    b = cv.getTrackbarPos('B','image')
    g = cv.getTrackbarPos('G','image')
    r = cv.getTrackbarPos('R','image')
    img[:]=[b,g,r]
    
cv.destroyAllWindows()

error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:2581: error: (-27:Null pointer) NULL window: 'image' in function 'cvGetTrackbarPos'


# HSV (Hue,Sturation and Value)

In [5]:
import cv2
import numpy as np
def nothing(x):
    pass
cv2.namedWindow("Tracking")
cv2.createTrackbar("LH","Tracking",0,255,nothing)
cv2.createTrackbar("LS","Tracking",0,255,nothing)
cv2.createTrackbar("LV","Tracking",0,255,nothing)
cv2.createTrackbar("UH","Tracking",255,255,nothing)
cv2.createTrackbar("US","Tracking",255,255,nothing)
cv2.createTrackbar("UV","Tracking",255,255,nothing)
while True:
    frame = cv2.imread('smarties.png')
    hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    l_h = cv2.getTrackbarPos("LH","Tracking")
    l_s = cv2.getTrackbarPos("LS","Tracking")
    l_v = cv2.getTrackbarPos("LV","Tracking")
    
    u_h = cv2.getTrackbarPos("UH","Tracking")
    u_s = cv2.getTrackbarPos("US","Tracking")
    u_v = cv2.getTrackbarPos("UV","Tracking")
    
    l_b = np.array([l_h,l_s,l_v])
    u_b = np.array([u_h,u_s,u_v])
    mask = cv2.inRange(hsv , l_b , u_b)
    res = cv2.bitwise_and(frame,frame,mask=mask)
    
    cv2.imshow('frame',frame)
    cv2.imshow('mask',mask)
    cv2.imshow('res',res)
    key = cv2.waitKey(1)
    if key==27:
        break
cv2.destroyAllWindows()

# ThreshHolding in openCV

In [8]:
#simple thresholding 
import cv2 as cv
import numpy as np
img = cv.imread('gradient.jfif',0)
_, th1 = cv.threshold(img,127,255,cv.THRESH_BINARY)
_, th2 = cv.threshold(img,127,255,cv.THRESH_BINARY_INV)
cv.imshow('image',img)
cv.imshow('th1',th1)
cv.imshow('th2',th2)
cv.waitKey(0)
cv.destroyAllWindows()

In [13]:
#adoptive thresholding
import cv2 as cv
import numpy as np
img = cv.imread("sudoku.png",0)
_, th1 = cv.threshold(img,127,255,cv.THRESH_BINARY)
th2 = cv.adaptiveThreshold(img,255,cv.ADAPTIVE_THRESH_MEAN_C,cv.THRESH_BINARY,11,2)
th3 = cv.adaptiveThreshold(img,255,cv.ADAPTIVE_THRESH_GAUSSIAN_C,cv.THRESH_BINARY,11,2)
cv.imshow('image',img)
cv.imshow('th1',th1)
cv.imshow('th2',th2)
cv.imshow('th3',th3)
cv.waitKey(0)
cv.destroyAllWindows()